### PR TITLE
Code study/generic client

### PR DESCRIPTION
**Pull request by renbauer-fnal**

### CODE REVIEW

**Review by ddbox — COMMENTED** [review]
I cannot read the module diagram in doc/module_diagrams/generic_client.
Is it a Diagram.net or some other format?

I think the changes to generic_client are good.  
host_addr.py has changes that I am still thinking about, its unfortunate there is not  yet a unit test to increase confidence

**Comment by ddbox** [comment]
On further review, I think the changes to hostaddr are good.  
The file in enstore/doc/module_diagrams/generic_client is indeed a diagram.net file.  It might be good to have a README in this directory saying as much in case all the current developers were hit by the same bus.

**Comment by ddbox** [comment]
a PR for test_hostaddr.py will come shortly

**Review by ddbox — APPROVED** [review]

**Comment by renbauer-fnal** [comment]
Thanks, Dennis. I thought about just removing the doc/module_diagrams directory since we haven't been adding to it otherwise. I don't think creating diagram.net diagrams for all of our modules is sustainable, so I don't see this becoming common. I saw you added a README, though, so it probably doesn't hurt to leave for now. We can repurpose this directory when we settle on a diagram tool (maybe pyreverse?)

**Pull request merged**
