### PR TITLE
Clean UDP pytests

### LINKED ISSUE #57: Implement unit tests to ~60% coverage

### PR DESCRIPTION
**Pull request by renbauer-fnal**
Add tests for cleanUDP module. I'll follow up to standardize on 4 space indents.

### CODE REVIEW

**Review by ddbox — CHANGES_REQUESTED** [review]
The reformatting of cleanUDP.py is an improvement IMO and the test module gives reasonable assurance that the changes are correct, with the possible exception of  cleanUDP.Select().  This test is essentially stubbed and will always pass even if Select() is changed catastrophically.
I note that cleanUDP.py has a  def __main__() which compares behavior of select.select() and cleanUDP.Select(), and does some basic socket i/o .  I attach a file test_Select.txt that includes my reformatting of the __main__()  so it runs under pytest on Linux.  
I request a change similar to (or better than) the one I attach to test_Select.  After this happens I approve of the merge.

**Review by ddbox — COMMENTED** [review]
[test_Select.txt](https://github.com/Enstore-org/enstore/files/8006759/test_Select.txt)

I forgot to attach the file I mentioned

**Comment by renbauer-fnal** [comment]
@ddbox , PTAL. I've updated the test_Select() method to your code, which is a definite improvement - I think I must have forgotten to fill in something useful there. AIUI this test will fail on any linux kernel which is sufficiently old (pre-2.4 kernel), is that expected and do you believe it is the best behavior? I could see skipping the test or making some guesses about how we expect it to behave as alternatives, but I suppose it is easy enough to skip this test (or ignore this failure) manually if we are for some reason testing on an ancient kernel / unfamiliar architecture.

I guess I'm only wondering if there is some reasonable and useful assertion we can make about what Select returns even if select.select returns something unexpected. I suppose Select should never return items which are not returned by select.select, but maybe that is not a useful property to test.

**Comment by ddbox** [comment]
I can't think of a good way to  change the tests to accommodate  other OS's than the linux we are developing on now.  Maybe its an exercise to be left to whoever ports it?  I also saw something about you wanted to look at some final indentation issues, so I took the liberty of running the changed files through autopep8 and will now merge and close the pull request

**Pull request merged**
